behaviors:
  PerformanceAgent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

    keep_checkpoints: 10

    max_steps: 500000

    time_horizon: 16

    summary_freq: 500

    threaded: false
